version: 2

models:
  - name: stg_yfinance_stocks_daily_actions
    materialized: view
    columns: 
      - name: date
        tests:
          - not_null

  - name: stg_yfinance_stocks_daily_prices
    materialized: view
    columns: 
      - name: date
        tests:
          - not_null
      

sources:
  - name: yfinance
    database: silencio-351022
    schema: stocks
    tables:
      - name: daily_prices
        loaded_at_field: run_date
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: daily_actions
        loaded_at_field: run_date
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}