version: 2

models:
  - name: stg_yfinance_stocks_daily_actions
    materialized: view
    columns: 
      - name: date
        tests:
          - not_null
      - name: source
        tests:
          - accepted_values:
              values:
                - yfinance
      - name: ticker
        tests:
          - relationships:
              to: ref('stg_yfinance_stocks_daily_prices')
              field: ticker

  - name: stg_yfinance_stocks_daily_prices
    materialized: view
    columns: 
      - name: date
        tests:
          - not_null
      - name: source
        tests:
          - accepted_values:
              values:
                - yfinance

  - name: stg_yfinance_stocks_annual_earnings
    materialized: view
    columns:
      - name: year
        tests:
          - not_null
      - name: ticker
        tests:
          - not_null
      
